export default {
  ETHEREUM_GO_ONLINE_ERROR: 'ETHEREUM_GO_ONLINE_ERROR',
  ETHEREUM_GO_ONLINE_START: 'ETHEREUM_GO_ONLINE_START',
  ETHEREUM_GO_ONLINE_SUCCESS: 'ETHEREUM_GO_ONLINE_SUCCESS',

  ETHEREUM_FETCH_CONTRACT_ERROR: 'ETHEREUM_FETCH_CONTRACT_ERROR',
  ETHEREUM_FETCH_CONTRACT_START: 'ETHEREUM_FETCH_CONTRACT_START',
  ETHEREUM_FETCH_CONTRACT_SUCCESS: 'ETHEREUM_FETCH_CONTRACT_SUCCESS',
}
