export default {
  ETHEREUM_GO_ONLINE_ERROR: 'ETHEREUM_GO_ONLINE_ERROR',
  ETHEREUM_GO_ONLINE_START: 'ETHEREUM_GO_ONLINE_START',
  ETHEREUM_GO_ONLINE_SUCCESS: 'ETHEREUM_GO_ONLINE_SUCCESS',

  ETHEREUM_CONTRACT_FETCH_ERROR: 'ETHEREUM_CONTRACT_FETCH_ERROR',
  ETHEREUM_CONTRACT_FETCH_START: 'ETHEREUM_CONTRACT_FETCH_START',
  ETHEREUM_CONTRACT_FETCH_SUCCESS: 'ETHEREUM_CONTRACT_FETCH_SUCCESS',
}
