export default {
  IPFS_CHANGE_IP_ADDRESS: 'IPFS_CHANGE_IP_ADDRESS',

  IPFS_GO_ONLINE_ERROR: 'IPFS_GO_ONLINE_ERROR',
  IPFS_GO_ONLINE_START: 'IPFS_GO_ONLINE_START',
  IPFS_GO_ONLINE_SUCCESS: 'IPFS_GO_ONLINE_SUCCESS',

  IPFS_UPDATE_VERSION: 'IPFS_UPDATE_VERSION',
};
