export default {
  MESSAGES_FETCH_START: 'MESSAGES_FETCH_START',
  MESSAGES_FETCH_SUCCESS: 'MESSAGES_FETCH_SUCCESS',
  MESSAGES_FETCH_ERROR: 'MESSAGES_FETCH_ERROR',

  ACTIVE_MESSAGE_SET: 'ACTIVE_MESSAGE_SET',
  ACTIVE_MESSAGE_CLEAR: 'ACTIVE_MESSAGE_CLEAR',

  ETHEREUM_GO_ONLINE_START: 'ETHEREUM_GO_ONLINE_START',
  ETHEREUM_GO_ONLINE_SUCCESS: 'ETHEREUM_GO_ONLINE_SUCCESS',
  ETHEREUM_GO_ONLINE_ERROR: 'ETHEREUM_GO_ONLINE_ERROR',

  IPFS_GO_ONLINE_START: 'IPFS_GO_ONLINE_START',
  IPFS_GO_ONLINE_SUCCESS: 'IPFS_GO_ONLINE_SUCCESS',
  IPFS_GO_ONLINE_ERROR: 'IPFS_GO_ONLINE_ERROR',
};
